# Generated by Django 5.1.2 on 2024-10-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_clean_sheets_player_passes_player_saves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='penalties_saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=50),
        ),
    ]
