# Generated by Django 5.1.2 on 2024-10-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goals_conceded',
            field=models.IntegerField(default=0),
        ),
    ]
