# Generated by Django 5.1.2 on 2024-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_player_goals_conceded'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='passes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tackles',
            field=models.IntegerField(default=0),
        ),
    ]
