# Generated by Django 5.1.2 on 2024-10-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_player_passes_player_tackles'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
