# Generated by Django 5.1.2 on 2024-10-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_player_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='passes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tackles',
        ),
        migrations.AddField(
            model_name='player',
            name='creativity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='influence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='threat',
            field=models.FloatField(default=0.0),
        ),
    ]
