# Generated by Django 5.1.2 on 2024-10-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_player_expected_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
